### ISSUE TITLE
storybook controls

### ISSUE THREAD

**Issue by joprice** [rowtype-yoga/ry-starter-spa#23]
Is it possible to get controls working for purescript components? I assume it normally uses propTypes or typescript definitions to figure it out, and I'm not aware of a way to generate either of these from a purescript component.

**Comment by i-am-the-slime** [comment]
I sat down this evening and tried to get 'em to work. I'm not really a fan of controls but rather exploding the combination in the story itself.
It would probably make a lot of sense to extract the whole storybook stuff into a library. So far I've been too lazy for that since there's barely any bindings.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1588055/107580669-30844100-6bf7-11eb-913e-4d13fd739caa.png">

The code looks something like this:

```purescript
module App.Components.Button.Stories (default, button) where

import App.Components.Button as Button
import App.Components.Button.View (Colour(..))
import Data.Maybe (Maybe(..))
import Debug.Trace (spy)
import Foreign (Foreign, unsafeToForeign)
import React.Basic (JSX, element)

default ∷ Foreign
default =
  unsafeToForeign
    { title: "Atoms/Button"
    , argTypes:
      { colour: { control: {type:  "color" }}
      , text: { type: "string", required: true }
      }
    }

button ∷
  { colour ∷ Colour
  , text ∷ String
  } ->
  JSX
button =
  withDefaultArgs { colour: Colour "#fcb", text: "Click me" } \args -> do
    element Button.component
      { text: args.text
      , colour: Just args.colour
      }

foreign import withDefaultArgs ∷
  ∀ args. args -> (args -> JSX) -> (args -> JSX)

-- FFI
-- exports.withDefaultArgs = args => x => 
--  { x.args = args 
--    return x
--  }
```


The theme will need to be adjusted too (that's what I struggled with the most):
In `manager.js` set `  isToolshown: true,`

And in `main.js`: `  addons: [ '@storybook/addon-controls'],`

As well as installing it in the first place with 
`yarn add -D @storybook/addon-controls`

Also make sure to update storybook

`npx sb@next upgrade`

Let me know how I can help further!

**Comment by i-am-the-slime** [comment]
@joprice does this help you?

**Comment by joprice** [comment]
Thank you! I'm new to storybooks and I was trying to figure out what the limits would be when using them from purescript. The two things I couldn't figure out is whether you'd have to define the argTypes, or if that is supposed to be deduced somehow, and how to set the `args` field on the component. I didn't realize you need `unsafeToForeign` in the first case, and I hadn't considered just using a mutating foreign call to set the field in the second. This is very helpful. 

For argTypes, I wonder if some generic programming could be used to walk the arg type and generate the "argTypes" object automatically.

**Comment by i-am-the-slime** [comment]
@joprice You don't actually need `unsafeToForeign`, the type signature is just quite useless. There should ideally be a type that ensures your `default` is of a shape that Storybook will understand. The only reason I use `unsafeToForeign` is because I didn't want to adjust the type signature all the time while experimenting :D.

As for the generic programming, yes that's probably doable but I'd prefer to have a typeclass for the most common PureScript types and newtypes thereof. However storybook controls controls currently are very limited and I'd love for support for custom ones to drop (maybe that's already possible with a plugin?).
If you'd like to start a dedicated storybook lib for PS, I'd be very interested in helping you out!

**Comment by joprice** [comment]
That makes sense. I'm still getting my toes wet with purescript so I'm not sure I'm committed enough yet to maintain a library, but I'll try this out and see where it goes. This repo helps me a lot with applied usage of many language features.
